### ISSUE TITLE
Minor error

### ISSUE THREAD

**Issue by badabing2005** [juleast/GeneratePIF#2]
![image](https://github.com/juleast/GeneratePIF/assets/22603312/f067ae39-a20c-410d-a70b-72037c2ae5ae)
I think it should be `device` instead of name.

I also believe that you can add
`ro.product.vendor.name`, `ro.product.vendor.device`, `ro.product.vendor.manufacturer`, `ro.product.vendor.brand`, `ro.product.vendor.model`, `ro.vendor.build.fingerprint` as lowest priority to their respective keys.

**Comment by juleast** [comment]
Thanks. I'll update those.
