### ISSUE TITLE
"bad array subscript" error on macOS

### ISSUE THREAD

**Issue by EstebanForge** [juleast/GeneratePIF#5]
Hi!

This is because macOS uses the very old 3.2 Bash. Even on Sonoma, with zsh, the script runs in bash because of the shebang #!/bin/bash

And that's ok, so the script can run on Android too.

But that causes this on macOS:

```
./start -m clone
Paste repo URL here (or press Ctrl+C to stop): https://dumps.tadiphone.dev/dumps/asus/XXX.git
./start: line 338: url_arr: bad array subscript
Cloning into 'XXX'...
```

And the entire rest of the script fails.

To fix it, first, line 338 and 339 should be like this:

```
    last_index=$(( ${#url_arr[@]} - 1 ))
    last_part="${url_arr[last_index]}"
    git_dir=(${last_part//.git/})
```

Then, lines 348, 349 and 350 should be:

```
    br=$(git rev-parse --abbrev-ref HEAD)
```

This changes fixes macOS errors, and allow the script to run on Linux (and Android) too.

Esteban

**Comment by EstebanForge** [comment]
Sent a PR https://github.com/juleast/GeneratePIF/pull/6

:)

**Comment by juleast** [comment]
Thanks, I'll review it. I haven't thought of MacOS since I seldom use it, but I do have a 2012 MBP that runs Ventura lying around. I didn't think it was too much of a cause for concern because I updated my bash using homebrew. I'll revert my bash to check the changes.
